// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/server/repository/metrics_repository/metrics_repository.go
//
// Generated by this command:
//
//	mockgen --source=pkg/server/repository/metrics_repository/metrics_repository.go --destination=test/mock/metrics_repository_mock.go --package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	metrics_repository "github.com/ovvesley/scik8sflow/pkg/server/repository/metrics_repository"
	gomock "go.uber.org/mock/gomock"
)

// MockIMetricsRepository is a mock of IMetricsRepository interface.
type MockIMetricsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIMetricsRepositoryMockRecorder
}

// MockIMetricsRepositoryMockRecorder is the mock recorder for MockIMetricsRepository.
type MockIMetricsRepositoryMockRecorder struct {
	mock *MockIMetricsRepository
}

// NewMockIMetricsRepository creates a new mock instance.
func NewMockIMetricsRepository(ctrl *gomock.Controller) *MockIMetricsRepository {
	mock := &MockIMetricsRepository{ctrl: ctrl}
	mock.recorder = &MockIMetricsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMetricsRepository) EXPECT() *MockIMetricsRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIMetricsRepository) Create(params metrics_repository.ParamsMetricsCreate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIMetricsRepositoryMockRecorder) Create(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIMetricsRepository)(nil).Create), params)
}
