// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/server/repository/storages_repository/storages_repository.go
//
// Generated by this command:
//
//	mockgen --source=pkg/server/repository/storages_repository/storages_repository.go --destination=test/mock/storages_repository_mock.go --package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	storages_repository "github.com/ovvesley/scik8sflow/pkg/server/repository/storages_repository"
	gomock "go.uber.org/mock/gomock"
)

// MockIStorageRepository is a mock of IStorageRepository interface.
type MockIStorageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIStorageRepositoryMockRecorder
}

// MockIStorageRepositoryMockRecorder is the mock recorder for MockIStorageRepository.
type MockIStorageRepositoryMockRecorder struct {
	mock *MockIStorageRepository
}

// NewMockIStorageRepository creates a new mock instance.
func NewMockIStorageRepository(ctrl *gomock.Controller) *MockIStorageRepository {
	mock := &MockIStorageRepository{ctrl: ctrl}
	mock.recorder = &MockIStorageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStorageRepository) EXPECT() *MockIStorageRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIStorageRepository) Create(params storages_repository.ParamsStorageCreate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIStorageRepositoryMockRecorder) Create(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIStorageRepository)(nil).Create), params)
}

// Find mocks base method.
func (m *MockIStorageRepository) Find(id int) (storages_repository.StorageDatabase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", id)
	ret0, _ := ret[0].(storages_repository.StorageDatabase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIStorageRepositoryMockRecorder) Find(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIStorageRepository)(nil).Find), id)
}

// Update mocks base method.
func (m *MockIStorageRepository) Update(params storages_repository.ParamsStorageUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIStorageRepositoryMockRecorder) Update(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIStorageRepository)(nil).Update), params)
}
