// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/server/repository/workflow_repository/workflow_repository.go
//
// Generated by this command:
//
//	mockgen --source=pkg/server/repository/workflow_repository/workflow_repository.go --destination=test/mock/workflow_repository_mock.go --package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	workflow "github.com/ovvesley/scientific-workflow-k8s/pkg/server/entities/workflow"
	gomock "go.uber.org/mock/gomock"
)

// MockIWorkflowRepository is a mock of IWorkflowRepository interface.
type MockIWorkflowRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIWorkflowRepositoryMockRecorder
}

// MockIWorkflowRepositoryMockRecorder is the mock recorder for MockIWorkflowRepository.
type MockIWorkflowRepositoryMockRecorder struct {
	mock *MockIWorkflowRepository
}

// NewMockIWorkflowRepository creates a new mock instance.
func NewMockIWorkflowRepository(ctrl *gomock.Controller) *MockIWorkflowRepository {
	mock := &MockIWorkflowRepository{ctrl: ctrl}
	mock.recorder = &MockIWorkflowRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWorkflowRepository) EXPECT() *MockIWorkflowRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIWorkflowRepository) Create(namespace string, workflow workflow.Workflow) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", namespace, workflow)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIWorkflowRepositoryMockRecorder) Create(namespace, workflow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIWorkflowRepository)(nil).Create), namespace, workflow)
}

// Find mocks base method.
func (m *MockIWorkflowRepository) Find(workflowId int) (workflow.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", workflowId)
	ret0, _ := ret[0].(workflow.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIWorkflowRepositoryMockRecorder) Find(workflowId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIWorkflowRepository)(nil).Find), workflowId)
}

// GetPendingWorkflows mocks base method.
func (m *MockIWorkflowRepository) GetPendingWorkflows(namespace string) ([]workflow.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingWorkflows", namespace)
	ret0, _ := ret[0].([]workflow.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingWorkflows indicates an expected call of GetPendingWorkflows.
func (mr *MockIWorkflowRepositoryMockRecorder) GetPendingWorkflows(namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingWorkflows", reflect.TypeOf((*MockIWorkflowRepository)(nil).GetPendingWorkflows), namespace)
}

// UpdateStatus mocks base method.
func (m *MockIWorkflowRepository) UpdateStatus(id, status int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockIWorkflowRepositoryMockRecorder) UpdateStatus(id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockIWorkflowRepository)(nil).UpdateStatus), id, status)
}
