apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-manager-deployment
  namespace: k8science-cluster-manager
  labels:
    app: cluster-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-manager
  template:
    metadata:
      labels:
        app: cluster-manager
    spec:
      containers:
        - name: cluster-manager
          image:  docker.io/ovvesley/uff-tcc-scientific-workflow-k8s:server
          env:
            - name: K8S_API_SERVER_HOST
              value: "https://kubernetes.default.svc"
            - name: K8S_API_SERVER_TOKEN
#              development value (not recommended for production)
              value: 'eyJhbGciOiJSUzI1NiIsImtpZCI6IkNxcGZ0Z1prSWtCYWxmaXB4YlRJZnc3a2lEc2c5dlczLUk5Vkh5TEF5TjgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjo1MzA5NDE2MzY5LCJpYXQiOjE3MDk0MTk5NjksImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrOHNjaWVuY2UtY2x1c3Rlci1tYW5hZ2VyIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImNsdXN0ZXItbWFuYWdlci1zYSIsInVpZCI6IjVkNjg2Y2NhLWUzNTMtNGE5YS1iNTNlLTRkMjUwMGFkYjdmMyJ9fSwibmJmIjoxNzA5NDE5OTY5LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6azhzY2llbmNlLWNsdXN0ZXItbWFuYWdlcjpjbHVzdGVyLW1hbmFnZXItc2EifQ.HwjXOKJaQdlw3XCSdfu5cTd5s-T6cmLj6XQWLVz134TukuMt5Rado9wdlDXM6F59XqKV_pNElMMeqREOTgLti_CWgyv5ELfWAjfO5o2PxbmyypT-TYEznrro8Nt-O_om4SOxzxIuXYJ4HGjmJ4wygq4fpX_qOOCD6HcPA0kQ3nVHaS8EUsxdlMgB8f7bE5jARS15etsaVFs4RJY5Dd65sm4_BMGYiYmdzwHcAubgxRlKMkbg_HAzLmA9gtB7I8c1slf-x4fSoIjyVrbjWns6kIasXhAUEXDDXyahTmZ3zR7cWUUCN3CRR4AFZG2iOtMy6VHyMKwqTBt--AyezNwK2g'

