apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-workflow-00
  namespace: scik8sflow
spec:
    replicas: 1
    selector:
        matchLabels:
          app: deployment-workflow-00
    template:
        metadata:
          labels:
              app: deployment-workflow-00
        spec:
            containers:
                - name: deployment-workflow-00
                  image: alpine:latest
                  command: ["sh", "-c", "while true; do echo $(date) >> /data/out.txt; sleep 1; done"]
                  volumeMounts:
                      - name: pvc-workflow-00
                        mountPath: /data
            restartPolicy: Always
            volumes:
                - name: pvc-workflow-00
                  persistentVolumeClaim:
                    claimName: pvc-workflow-00