apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-workflow-00
  namespace: scik8sflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Mi
  storageClassName: hostpath
