package validation

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// TestFixtureImageReferencesResolve walks every shipped workflow.yaml and
// checks that any OCI image reference it declares actually has a Dockerfile
// inside the example's docker/ directory. Showcase workflows reference images
// that are published to ghcr.io (no local Dockerfile expected). The check is
// therefore scoped to references that are NOT pinned to a registry we publish
// to and NOT a stock public image.
func TestFixtureImageReferencesResolve(t *testing.T) {
	root := repositoryRoot(t)
	fixtures, err := DiscoverFixtures(root)
	require.NoError(t, err)
	var failures []string
	for _, name := range fixtures.SortedNames() {
		category := fixtures[name]
		if !category.HasFile("workflow.yaml") {
			continue
		}
		payload, err := category.ReadFile("workflow.yaml")
		require.NoError(t, err)
		references := collectImageReferences(payload)
		if len(references) == 0 {
			continue
		}
		dockerDir := filepath.Join(category.Directory, "docker")
		if _, err := os.Stat(dockerDir); err != nil {
			// No docker dir is acceptable for fixtures that intentionally use
			// public images (e.g. direct-hello uses busybox:1.36).
			continue
		}
		images := collectDockerfileImages(dockerDir)
		for _, reference := range references {
			if isPublicImage(reference) || isShowcaseImage(reference) {
				continue
			}
			if _, ok := images[shortImage(reference)]; !ok {
				failures = append(failures, fmt.Sprintf(
					"[%s] workflow.yaml references image %q but docker/ does not declare it",
					name, reference))
			}
		}
	}
	if len(failures) > 0 {
		t.Fatalf("image references without matching Dockerfiles:\n%s", strings.Join(failures, "\n"))
	}
}

// TestFixtureReadmeMentionsWorkflow walks every fixture with a README.md and
// confirms the README references the workflow.yaml file the fixture ships.
// READMEs are allowed to mention only the primary artefact because the
// support files (scope.yaml, topology.yaml, ...) are auto-generated by
// `run.sh` from the workflow in the showcase category.
func TestFixtureReadmeMentionsWorkflow(t *testing.T) {
	root := repositoryRoot(t)
	fixtures, err := DiscoverFixtures(root)
	require.NoError(t, err)
	var failures []string
	for _, name := range fixtures.SortedNames() {
		category := fixtures[name]
		if !category.HasFile("README.md") || !category.HasFile("workflow.yaml") {
			continue
		}
		readme, err := category.ReadFile("README.md")
		require.NoError(t, err)
		// Accept either a literal "workflow.yaml" reference or a code-fenced
		// shell snippet that uses the file (./run.sh, workflow.yaml).
		if !strings.Contains(readme, "workflow.yaml") && !strings.Contains(readme, "run.sh") {
			failures = append(failures, fmt.Sprintf(
				"[%s] README.md does not mention workflow.yaml or run.sh even though the fixture ships it",
				name))
		}
	}
	if len(failures) > 0 {
		t.Fatalf("README drift detected:\n%s", strings.Join(failures, "\n"))
	}
}

func collectImageReferences(payload string) []string {
	references := make([]string, 0)
	// Lightweight parser: we only need the "image:" key anywhere in the YAML.
	for _, line := range strings.Split(payload, "\n") {
		trimmed := strings.TrimSpace(line)
		if !strings.HasPrefix(trimmed, "image:") {
			continue
		}
		value := strings.TrimSpace(strings.TrimPrefix(trimmed, "image:"))
		value = strings.Trim(value, "\"'")
		if value != "" {
			references = append(references, value)
		}
	}
	return references
}

func collectDockerfileImages(dockerDir string) map[string]bool {
	images := map[string]bool{}
	entries, err := os.ReadDir(dockerDir)
	if err != nil {
		return images
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if !strings.EqualFold(entry.Name(), "Dockerfile") {
			continue
		}
		payload, err := os.ReadFile(filepath.Join(dockerDir, entry.Name()))
		if err != nil {
			continue
		}
		for _, line := range strings.Split(string(payload), "\n") {
			trimmed := strings.TrimSpace(line)
			if !strings.HasPrefix(strings.ToUpper(trimmed), "FROM") {
				continue
			}
			parts := strings.Fields(trimmed)
			if len(parts) < 2 {
				continue
			}
			images[shortImage(parts[1])] = true
		}
	}
	return images
}

// shortImage strips the registry prefix and tag from an image reference.
func shortImage(reference string) string {
	reference = strings.TrimPrefix(reference, "docker.io/library/")
	reference = strings.TrimPrefix(reference, "docker.io/")
	if idx := strings.LastIndex(reference, ":"); idx > strings.LastIndex(reference, "/") {
		reference = reference[:idx]
	}
	if idx := strings.LastIndex(reference, "@"); idx > strings.LastIndex(reference, "/") {
		reference = reference[:idx]
	}
	return reference
}

// isPublicImage returns true for upstream images that the fixture does not
// need to build: busybox, alpine, ubuntu, etc.
func isPublicImage(reference string) bool {
	publicPrefixes := []string{"busybox:", "alpine:", "ubuntu:", "debian:", "python:", "golang:"}
	for _, prefix := range publicPrefixes {
		if strings.HasPrefix(reference, prefix) {
			return true
		}
	}
	return strings.HasSuffix(reference, ":latest") || strings.Contains(reference, "/library/")
}

// isShowcaseImage returns true for the published showcase images that are
// pushed to ghcr.io by the showcase workflow and not built per-fixture.
func isShowcaseImage(reference string) bool {
	return strings.HasPrefix(reference, "ghcr.io/uffescience/")
}
