apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: akoflow-data
  namespace: akoflow
  labels:
    app.kubernetes.io/managed-by: akoflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
