name: simgrid-50core-workers
spec:
  namespace: examples
  activities:
    - name: worker-001
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-002
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-003
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-004
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-005
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-006
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-007
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-008
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-009
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-010
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-011
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-012
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-013
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-014
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-015
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-016
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-017
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-018
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-019
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-020
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-021
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-022
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-023
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-024
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-025
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-026
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-027
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-028
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-029
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-030
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-031
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-032
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-033
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-034
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-035
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-036
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-037
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-038
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-039
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-040
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-041
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-042
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-043
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-044
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-045
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-046
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-047
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-048
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-049
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-050
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-051
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-052
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-053
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-054
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-055
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-056
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-057
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-058
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-059
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-060
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-061
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-062
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-063
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-064
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-065
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-066
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-067
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-068
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-069
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-070
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-071
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-072
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-073
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-074
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-075
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-076
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-077
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-078
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-079
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-080
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-081
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-082
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-083
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-084
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-085
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-086
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-087
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-088
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-089
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-090
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-091
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-092
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-093
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-094
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-095
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-096
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-097
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-098
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-099
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
    - name: worker-100
      runtime: simgrid-50core
      cpuLimit: "1"
      memoryLimit: 1Gi
      simulation: {model: deterministic, durationSeconds: 10}
  dataDependencies: []
