import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "category",
      label: "Tutorials",
      collapsed: false,
      items: [
        "getting-started",
        "installation",
        "downloads",
        "guides/interface-tour",
        "guides/workflows/first-local-run",
        "guides/workflows/first-run",
        {
          type: "category",
          label: "Connect execution infrastructure",
          items: ["tutorials/register-hpc", "tutorials/connect-cloud"],
        },
        {
          type: "category",
          label: "Workflow showcases",
          collapsed: true,
          items: [
            "showcase/index",
            {
              type: "category",
              label: "Simple examples",
              collapsed: true,
              items: [
                "showcase/edge-cloud-simulation",
                "showcase/kubernetes-real-execution",
                "showcase/hybrid-cloud-transfer",
                "showcase/local-direct-execution",
                "showcase/slurm-local-fixture",
                "showcase/network-fanout",
                "showcase/parallel-50-core",
              ],
            },
            {
              type: "category",
              label: "Machine Learning",
              collapsed: true,
              items: [
                "showcase/ai/machine-learning/index",
                "showcase/ai/machine-learning/training-with-mlflow",
                "showcase/ai/machine-learning/hyperparameter-search",
                "showcase/ai/machine-learning/lora-fine-tuning",
                "showcase/ai/machine-learning/batch-inference",
                "showcase/ai/machine-learning/model-comparison",
                "showcase/ai/machine-learning/model-conversion",
                "showcase/ai/machine-learning/computer-vision",
                "showcase/ai/machine-learning/anomaly-detection",
                "showcase/ai/machine-learning/model-ensemble",
                "showcase/ai/machine-learning/model-distillation",
                "showcase/ai/machine-learning/inference-benchmark",
                "showcase/ai/machine-learning/infrastructure-selection",
              ],
            },
            {
              type: "category",
              label: "Generative AI",
              collapsed: true,
              items: [
                "showcase/ai/generative-ai/index",
                "showcase/ai/generative-ai/rag-indexing",
                "showcase/ai/generative-ai/synthetic-dataset",
                "showcase/ai/generative-ai/audio-transcription",
                "showcase/ai/generative-ai/document-extraction",
              ],
            },
            {
              type: "category",
              label: "Agentic workflows",
              collapsed: true,
              items: [
                "showcase/ai/agentic-workflows/index",
                "showcase/ai/agentic-workflows/bounded-agent",
                "showcase/ai/agentic-workflows/supervised-tool-loop",
                "showcase/ai/agentic-workflows/multi-agent-review",
              ],
            },
            {
              type: "category",
              label: "Scientific AI",
              collapsed: true,
              items: [
                "showcase/ai/scientific-ai/index",
                "showcase/ai/scientific-ai/ai-assisted-analysis",
                "showcase/ai/scientific-ai/surrogate-model",
                "showcase/ai/scientific-ai/experiment-feedback-loop",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "How-to guides",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Workflows",
          collapsed: true,
          items: [
            "guides/workflows/definitions",
            "guides/workflows/planning",
            "guides/workflows/executions",
          ],
        },
        {
          type: "category",
          label: "Infrastructure",
          collapsed: true,
          items: [
            "guides/infrastructure/environments",
            "guides/infrastructure/simgrid",
            "guides/infrastructure/kubernetes",
            "guides/infrastructure/execution-scopes",
            "guides/infrastructure/storage",
            "guides/infrastructure/cloud-support",
            "guides/infrastructure/cloud-capacity",
            "guides/infrastructure/machine-configurations",
            "guides/infrastructure/gcp",
            "guides/infrastructure/aws",
            "guides/infrastructure/hpc-slurm",
          ],
        },
        {
          type: "category",
          label: "Data and evidence",
          collapsed: true,
          items: [
            "guides/data/artifacts",
            "guides/data/build-executable",
            "guides/data/artifact-locations",
            "guides/data/provenance-and-audit",
            "guides/data/provenance",
            "guides/data/audit-events",
          ],
        },
        {
          type: "category",
          label: "Operations",
          collapsed: true,
          items: [
            "guides/operations/instance-management",
            "guides/operations/personal-preferences",
            "guides/operations/server-instance",
            "guides/operations/search-and-notifications",
            "guides/operations/find-records",
            "guides/operations/follow-notifications",
            "guides/operations/interactive-console",
            "guides/operations/credentials-and-ssh",
            "guides/operations/troubleshooting",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Explanations",
      collapsed: false,
      items: [
        "concepts",
        "explanations/planning",
        "explanations/prism-and-heft",
        "explanations/network-modeling",
        "explanations/evidence-and-provenance",
        "explanations/observed-timing",
      ],
    },
    {
      type: "category",
      label: "Developing AkôFlow",
      collapsed: true,
      items: ["modules", "engine", "runtimes"],
    },
    {
      type: "category",
      label: "Reference",
      collapsed: false,
      items: [
        "tutorials/api-access",
        "reference/api-overview",
        "reference/environment-yaml",
        "reference/execution-scopes-and-topologies",
        "reference/planning-and-execution-states",
        "reference/feature-coverage",
        "internal/workflow-spec",
        {
          type: "category",
          label: "API endpoints",
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "api/endpoints" }],
        },
      ],
    },
    {
      type: "category",
      label: "Contributing",
      collapsed: true,
      items: ["contributing/documentation-plan"],
    },
  ],
};

export default sidebars;
