import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "category",
      label: "Tutorials",
      collapsed: false,
      items: [
        "getting-started",
        "installation",
        "downloads",
        "guides/interface-tour",
        "guides/workflows/first-run",
        {
          type: "category",
          label: "Workflow showcases",
          collapsed: true,
          items: [
            "showcase/index",
            "showcase/edge-cloud-simulation",
            "showcase/kubernetes-real-execution",
            "showcase/network-fanout",
            "showcase/parallel-50-core",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "How-to guides",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Workflows",
          collapsed: true,
          items: [
            "guides/workflows/definitions",
            "guides/workflows/planning",
            "guides/workflows/executions",
          ],
        },
        {
          type: "category",
          label: "Infrastructure",
          collapsed: true,
          items: [
            "guides/infrastructure/environments",
            "guides/infrastructure/simgrid",
            "guides/infrastructure/kubernetes",
            "guides/infrastructure/execution-scopes",
            "guides/infrastructure/storage",
            "guides/infrastructure/cloud-capacity",
            "guides/infrastructure/gcp",
            "guides/infrastructure/aws",
            "guides/infrastructure/hpc-slurm",
          ],
        },
        {
          type: "category",
          label: "Data and evidence",
          collapsed: true,
          items: ["guides/data/artifacts", "guides/data/provenance-and-audit"],
        },
        {
          type: "category",
          label: "Operations",
          collapsed: true,
          items: [
            "guides/operations/instance-management",
            "guides/operations/search-and-notifications",
            "guides/operations/interactive-console",
            "guides/operations/credentials-and-ssh",
            "guides/operations/troubleshooting",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Explanations",
      collapsed: false,
      items: [
        "modules",
        "concepts",
        "engine",
        "runtimes",
        "explanations/planning",
        "explanations/prism-and-heft",
        "explanations/network-modeling",
        "explanations/evidence-and-provenance",
        "explanations/observed-timing",
      ],
    },
    {
      type: "category",
      label: "Reference",
      collapsed: false,
      items: [
        "reference/api-overview",
        "reference/environment-yaml",
        "reference/execution-scopes-and-topologies",
        "reference/planning-and-execution-states",
        {
          type: "category",
          label: "API endpoints",
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "api/endpoints" }],
        },
        "internal/workflow-spec",
        "cli",
      ],
    },
    {
      type: "category",
      label: "Contributing",
      collapsed: true,
      items: ["contributing/documentation-plan"],
    },
  ],
};

export default sidebars;
